# Generated by Django 5.0.6 on 2024-07-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_employye_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employye',
            new_name='Employee',
        ),
    ]
