# Generated by Django 5.0.6 on 2024-07-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Att_id', models.IntegerField(max_length=10)),
                ('employee_id', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=20)),
                ('yes_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=255),
        ),
    ]
