# Generated by Django 5.0.6 on 2024-07-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='YESorNO',
            new_name='present',
        ),
    ]
